import './globals.css'
import { Exo } from 'next/font/google'
import React from 'react'
import Footer from './components/Footer'
import Navbar from './components/Navbar'

const exo = Exo({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={exo.className + " bg-primary" + " text-primary-content"} data-theme='dark'>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
