import "./globals.css";
import { Exo } from "next/font/google";
import React from "react";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import PageWrapper from "./components/PageWrapper";
import SpaceBackground from "./components/SpaceBackground";

const exo = Exo({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={exo.className + " bg-primary" + " text-primary-content"}
        data-theme="dark"
      >
        <div className="flex flex-col h-screen">
          <SpaceBackground />
          <Navbar />
          <PageWrapper>
            {children}
          </PageWrapper>
          <Footer />
        </div>
      </body>
    </html>
  );
}
