'use client'
import './globals.css'
import { Exo } from 'next/font/google'
import React from 'react'

const exo = Exo({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className={exo.className + " bg-black" + " text-white"}>{children}</body>
    </html>
  )
}
